### ISSUE TITLE
March meeting info

### ISSUE THREAD

**Issue by bertwagner** [OhioNorthDatabaseTraining/Admin#13]
@erinstellato I made you a co organizer of the Meetup page, allowing you to create events.  Do you want to post the March meeting info on Meetup, and then I can post it everywhere else?

**Comment by erinstellato** [comment]
@bertwagner I can do that, and write the blog post.  Do I know the access info for Meetup?  :)

**Comment by bertwagner** [comment]
@erinstellato I made your account a "Co Organizer", so when you login to Meetup you should have permission to create a new event.  If not, let me know.
![image](https://user-images.githubusercontent.com/4317083/108392093-5bb2f580-71e0-11eb-9a30-270fe5961475.png)

**Comment by erinstellato** [comment]
Meetup link: https://www.meetup.com/ohio-north-database-training/events/276447531/

Blog post: https://ondt.org/?p=306

**Comment by bertwagner** [comment]
Thanks!
